# Generated by Django 5.0.1 on 2026-01-10 15:24

from django.db import migrations, models

# Conditional ckeditor import - fallback to TextField if not installed
try:
    import ckeditor.fields
    RichTextField = ckeditor.fields.RichTextField
except ImportError:
    # Create a wrapper that returns TextField when ckeditor is not available
    class RichTextFieldFallback(models.TextField):
        pass
    RichTextField = RichTextFieldFallback


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug URL')),
                ('system_type', models.CharField(choices=[('aquaponie', 'Aquaponie'), ('hydroponie', 'Hydroponie'), ('pisciculture', 'Pisciculture')], default='aquaponie', max_length=20, verbose_name='Type de système')),
                ('description', models.TextField(verbose_name='Description')),
                ('full_description', RichTextField(blank=True, verbose_name='Description complète')),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Longueur (m)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Largeur (m)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Hauteur (m)')),
                ('fish_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité poissons')),
                ('plant_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité plantes')),
                ('water_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Volume d'eau (L)")),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix (FCFA)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ancien prix (barré)')),
                ('image', models.ImageField(upload_to='systems/', verbose_name='Image principale')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='systems/', verbose_name='Image 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='systems/', verbose_name='Image 3')),
                ('features', models.TextField(blank=True, verbose_name='Caractéristiques (une par ligne)')),
                ('includes', models.TextField(blank=True, verbose_name='Inclus dans le kit (un par ligne)')),
                ('target_audience', models.CharField(default='Ménages', max_length=100, verbose_name='Public cible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Modèle vedette')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Modèle de système',
                'verbose_name_plural': 'Modèles de systèmes',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
