# Generated by Django 5.0.1 on 2026-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du prix/distinction')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisation/Concours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('image', models.ImageField(blank=True, null=True, upload_to='awards/', verbose_name='Image/Logo')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='awards/certificates/', verbose_name='Certificat/Diplôme')),
                ('url', models.URLField(blank=True, verbose_name='Lien externe')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Distinction/Prix',
                'verbose_name_plural': 'Distinctions et Prix',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image À propos 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image À propos 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image À propos 3'),
        ),
    ]
