# Generated by Django 5.0.1 on 2026-01-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_basintype_croptype_fishspecies_hydrosystemtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(choices=[('#00bcd4,#0097a7', 'Cyan'), ('#4caf50,#2e7d32', 'Vert'), ('#1976d2,#0d47a1', 'Bleu'), ('#ff9800,#f57c00', 'Orange'), ('#9c27b0,#7b1fa2', 'Violet'), ('#e91e63,#c2185b', 'Rose'), ('#607d8b,#455a64', 'Gris'), ('#f44336,#c62828', 'Rouge'), ('#795548,#4e342e', 'Marron')], default='#4caf50,#2e7d32', max_length=30, verbose_name='Couleur du dégradé'),
        ),
        migrations.AddField(
            model_name='service',
            name='link_text',
            field=models.CharField(default='En savoir plus', max_length=50, verbose_name='Texte du lien'),
        ),
        migrations.AddField(
            model_name='service',
            name='link_url',
            field=models.CharField(blank=True, help_text='Ex: /devis/aquaponie/ ou #contact', max_length=200, verbose_name='URL du lien'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='fa fa-leaf', help_text='Ex: fa fa-leaf, fa fa-cogs, fa fa-graduation-cap', max_length=50, verbose_name='Classe icône (FontAwesome)'),
        ),
    ]
