# Generated by Django 5.0.1 on 2026-01-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_service_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('quiz_score', models.PositiveIntegerField(default=0, verbose_name='Score au quiz')),
                ('quiz_total', models.PositiveIntegerField(default=4, verbose_name='Nombre de questions')),
                ('prize_won', models.CharField(blank=True, choices=[('10_percent', '10% de réduction'), ('15_percent', '15% de réduction'), ('free_delivery', 'Livraison gratuite'), ('free_guide', 'Guide PDF gratuit'), ('free_consultation', 'Consultation gratuite 30min'), ('lost', 'Pas de gain')], max_length=50, verbose_name='Prix gagné')),
                ('promo_code', models.CharField(blank=True, max_length=20, verbose_name='Code promo')),
                ('has_used_prize', models.BooleanField(default=False, verbose_name='Prix utilisé')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': 'Participation au jeu',
                'verbose_name_plural': 'Participations au jeu',
                'ordering': ['-created_at'],
            },
        ),
    ]
