# Generated by Django 5.0.1 on 2026-01-11 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_game_participation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('option_1', models.CharField(max_length=300, verbose_name='Option 1')),
                ('option_2', models.CharField(max_length=300, verbose_name='Option 2')),
                ('option_3', models.CharField(max_length=300, verbose_name='Option 3')),
                ('option_4', models.CharField(max_length=300, verbose_name='Option 4')),
                ('correct_option', models.PositiveIntegerField(default=1, help_text="Numéro de l'option correcte (1, 2, 3 ou 4)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Réponse correcte (1-4)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Question du quiz',
                'verbose_name_plural': 'Questions du quiz',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
