# Generated by Django 5.0.1 on 2026-01-11 01:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_quiz_question_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du prix')),
                ('prize_type', models.CharField(choices=[('discount', 'Réduction (%)'), ('free_delivery', 'Livraison gratuite'), ('free_item', 'Article gratuit'), ('lost', 'Pas de chance')], default='discount', max_length=20, verbose_name='Type de prix')),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text="Uniquement pour les prix de type 'Réduction'", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de réduction')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#4caf50', help_text='Code couleur hex (ex: #4caf50)', max_length=7, verbose_name='Couleur sur la roue')),
                ('icon', models.CharField(default='🎁', max_length=10, verbose_name='Emoji/Icône')),
                ('applies_to_fresh_products_only', models.BooleanField(default=True, help_text="Si coché, la réduction ne s'applique qu'aux produits frais", verbose_name='Applicable uniquement aux produits frais')),
                ('is_winning_prize', models.BooleanField(default=True, help_text="Décochez pour les cases 'Pas de chance'", verbose_name='Est un prix gagnant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Position sur la roue (0-7)')),
            ],
            options={
                'verbose_name': 'Prix de la roue',
                'verbose_name_plural': 'Prix de la roue',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='gameparticipation',
            name='prize_won',
        ),
        migrations.AddField(
            model_name='gameparticipation',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='core.gameprize', verbose_name='Prix gagné'),
        ),
    ]
